"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# Environment Variables
# =============================================================================

# SECRET_KEY and DEBUG
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key')
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# Allowed Hosts - ensure there's always a valid host
allowed_hosts_str = os.getenv("ALLOWED_HOSTS", "*")
ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_str.split(",") if h.strip()] or ["*"]

# =============================================================================
# CORS Configuration
# =============================================================================
# For production with ClawCloud and Netlify, allow all origins temporarily
# to debug, then restrict once working
CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "True").lower() == "true"

# If you want to restrict origins, set CORS_ALLOW_ALL_ORIGINS=False and configure these:
cors_origins = os.getenv("CORS_ALLOWED_ORIGINS", "")
if cors_origins:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins.split(",") if origin.strip()]

# Always allow credentials
CORS_ALLOW_CREDENTIALS = True

# Expose headers to the browser
CORS_EXPOSE_HEADERS = [
    "Content-Type",
    "X-CSRFToken",
]

# Allow all common headers and methods for CORS
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# Preflight cache duration (1 hour)
CORS_PREFLIGHT_MAX_AGE = 3600

# =============================================================================
# CSRF Configuration
# =============================================================================
csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins.split(",") if origin.strip()]

# For APIs, you might want to exempt CSRF for certain views
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False

# =============================================================================
# Static and Media
# =============================================================================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# =============================================================================
# Application definition
# =============================================================================
INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    # Third-party
    'rest_framework',
    'drf_spectacular',

    # Local apps
    'apps.users.apps.UsersConfig',
    'apps.projects.apps.ProjectsConfig',
    'apps.documents.apps.DocumentsConfig',
    'apps.bids.apps.BidsConfig',
    'apps.ai_engine.apps.AiEngineConfig',
    'apps.core.apps.CoreConfig',
    'apps.services.apps.ServicesConfig',
    'apps.messaging.apps.MessagingConfig',
    'common',

    # JWT Auth app
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be first for CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# =============================================================================
# Database
# =============================================================================
DATABASES = {
    'default': {
        'ENGINE': os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
        'OPTIONS': {
            'sslmode': os.getenv("DB_SSLMODE", "require")
        }
    }
}

# =============================================================================
# Authentication
# =============================================================================
AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# =============================================================================
# Internationalization
# =============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# =============================================================================
# REST Framework
# =============================================================================
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'common.exceptions.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'login': '20/hour',
        'register': '10/hour',
        'admin': '1000/hour',
        'proposal_write': '20/hour',
        'proposal_read': '200/hour',
        'document_upload': '20/hour',
        'document_read': '200/hour',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Tender Pilot API',
    'DESCRIPTION': 'Backend API for Tender Pilot platform',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [{'bearerAuth': []}],
    'SECURITY_DEFINITIONS': {
        'bearerAuth': {'type': 'http', 'scheme': 'bearer', 'bearerFormat': 'JWT',}
    },
}

# =============================================================================
# JWT Settings
# =============================================================================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# =============================================================================
# AI Engine
# =============================================================================
AI_DEFAULT_PROVIDER = os.getenv('AI_DEFAULT_PROVIDER', 'openai')
AI_DEFAULT_MODEL = os.getenv('AI_DEFAULT_MODEL', 'gpt-4o-mini')

AI_PROVIDERS = {
    'openai': {
        'api_key': os.getenv('OPENAI_API_KEY'),
        'default_model': os.getenv('AI_DEFAULT_MODEL', 'gpt-4o-mini'),
        'organization_id': os.getenv('OPENAI_ORGANIZATION_ID'),
        'timeout': float(os.getenv('OPENAI_TIMEOUT', '60.0')),
    },
    'gemini': {
        'api_key': os.getenv('GEMINI_API_KEY'),
        'default_model': os.getenv('GEMINI_DEFAULT_MODEL', 'gemini-2.5-flash'),
        'timeout': float(os.getenv('GEMINI_TIMEOUT', '60.0')),
    },
}

AI_RATE_LIMITS = {
    'requests_per_hour': int(os.getenv('AI_REQUESTS_PER_HOUR', '50')),
    'tokens_per_day': int(os.getenv('AI_TOKENS_PER_DAY', '100000')),
    'cost_per_day': float(os.getenv('AI_COST_PER_DAY', '10.0')),
}

AI_MODEL_PRICING = {
    'gpt-4': {'input': 0.03, 'output': 0.06},
    'gpt-4-turbo': {'input': 0.01, 'output': 0.03},
    'gpt-4o': {'input': 0.005, 'output': 0.015},
    'gpt-4o-mini': {'input': 0.00015, 'output': 0.0006},
    'gpt-3.5-turbo': {'input': 0.0005, 'output': 0.0015},
    'gemini-2.5-flash': {'input': 0.0, 'output': 0.0},
    'gemini-1.5-pro': {'input': 0.00125, 'output': 0.005},
    'gemini-1.5-flash': {'input': 0.000075, 'output': 0.0003},
    'gemini-1.0-pro': {'input': 0.0005, 'output': 0.0015},
    'claude-3-opus': {'input': 0.015, 'output': 0.075},
    'claude-3-sonnet': {'input': 0.003, 'output': 0.015},
    'claude-3-haiku': {'input': 0.00025, 'output': 0.00125},
}

AI_FEATURES = {
    'enabled': os.getenv('AI_ENABLED', 'True').lower() == 'true',
    'tender_analysis': True,
    'compliance_check': True,
    'proposal_generation': True,
    'allow_caching': True,
    'cache_ttl': 3600,
}

AI_CIRCUIT_BREAKER = {
    'failure_threshold': 5,
    'success_threshold': 2,
    'timeout': 60.0,
}

# =============================================================================
# Default primary key field type
# =============================================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
